development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: private_events
  pool: 5
  username: hemashri
  password: password
  host: localhost
  port: 5432
  template: template0
